### ISSUE TITLE
Package name 

### ISSUE THREAD

**Issue by ahmednfwela** [meilisearch/meilisearch-flutter#2]
What name to use for the new package on pub.dev? Since we already have meilisearch, I suggest naming it meilisearch_ui

Cc @brunoocasali

**Comment by brunoocasali** [comment]
I like the suggestion, but what do you think of `meilisearch_flutter`? Or is it redundant?

**Comment by ahmednfwela** [comment]
I thought of that at first but I think it's redundant, also firebase use the UI naming pattern instead of just flutter

**Comment by brunoocasali** [comment]
It is good for me, let's go with `meilisearch_ui` ;)
